---
framework:
  AdminMode: 0
  LogLevel: DEBUG
  Database:
    Version: 0.0.2
  Plugins:
    - LetMe: {}
    - User: {}
    - Authentication::Password:
        login_by: username
 #       login_by: email
